#!/usr/bin/env bash
# install nginx to create html pages - 404
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
ERRDIR="\\\n\terror_page 404 /var/www/html/custom_404.html;\n\tlocation = /var/www/html/custom_404.html {\n\t\tinternal;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "48i $ERRDIR" $SRC
sudo service nginx restart
