#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# with the help of 'sed' command
apt-get -y update
apt-get -y install nginx
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
