#!/usr/bin/env bash
# install load balancer and configures HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo -e "\nfrontend http-in" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 111191-web-01 54.90.3.149:80 check" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 111191-web-02 75.101.217.125:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
